-- Align BIGINT columns to UNSIGNED to match schema and avoid FK incompatibilities
-- Safe to run on existing databases; will only alter if signed

-- Temporarily disable FK checks during type alignment (note: MySQL still validates metadata on ALTER)
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

-- 1) First, alter all columns that REFERENCE USERS(user_id)
ALTER TABLE ONLINE_ORDERS       MODIFY COLUMN customer_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE CUSTOMER_ADDRESSES  MODIFY COLUMN customer_id BIGINT UNSIGNED NOT NULL;
ALTER TABLE TRANSACTIONS        MODIFY COLUMN customer_id BIGINT UNSIGNED NULL;
ALTER TABLE TRANSACTIONS        MODIFY COLUMN user_id     BIGINT UNSIGNED NOT NULL;
ALTER TABLE SESSION_TOKENS      MODIFY COLUMN user_id     BIGINT UNSIGNED NOT NULL;
ALTER TABLE CART_ITEMS          MODIFY COLUMN customer_id BIGINT UNSIGNED NOT NULL;
-- AUDIT_LOG is optional but included for completeness
ALTER TABLE AUDIT_LOG           MODIFY COLUMN user_id     BIGINT UNSIGNED NULL;

-- 2) Now alter USERS PK
ALTER TABLE USERS               MODIFY COLUMN user_id     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 3) Alter all columns that REFERENCE PRODUCTS(product_id)
ALTER TABLE ONLINE_PRODUCTS     MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL;
ALTER TABLE INVENTORY           MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL;
ALTER TABLE TRANSACTION_ITEMS   MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL;
ALTER TABLE RETURNS             MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL;
ALTER TABLE STOCK_MOVEMENTS     MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL;
ALTER TABLE CART_ITEMS          MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL;

-- 4) Now alter PRODUCTS PK
ALTER TABLE PRODUCTS            MODIFY COLUMN product_id  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 5) Alter all columns that REFERENCE TRANSACTIONS(transaction_id)
ALTER TABLE ONLINE_ORDERS       MODIFY COLUMN transaction_id           BIGINT UNSIGNED NOT NULL;
ALTER TABLE TRANSACTION_ITEMS   MODIFY COLUMN transaction_id           BIGINT UNSIGNED NOT NULL;
ALTER TABLE PAYMENTS            MODIFY COLUMN transaction_id           BIGINT UNSIGNED NOT NULL;
ALTER TABLE RETURNS             MODIFY COLUMN original_transaction_id  BIGINT UNSIGNED NOT NULL;
ALTER TABLE RETURNS             MODIFY COLUMN return_transaction_id    BIGINT UNSIGNED NULL;
ALTER TABLE STOCK_MOVEMENTS     MODIFY COLUMN transaction_id           BIGINT UNSIGNED NULL;
ALTER TABLE EMAIL_LOGS          MODIFY COLUMN transaction_id           BIGINT UNSIGNED NULL;

-- 6) Now alter TRANSACTIONS PK
ALTER TABLE TRANSACTIONS        MODIFY COLUMN transaction_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 7) Alter columns that REFERENCE CUSTOMER_ADDRESSES(address_id)
ALTER TABLE ONLINE_ORDERS       MODIFY COLUMN shipping_address_id BIGINT UNSIGNED NULL;

-- 8) Now alter CUSTOMER_ADDRESSES PK
ALTER TABLE CUSTOMER_ADDRESSES  MODIFY COLUMN address_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

-- 9) Update remaining table primary keys (not referenced by others or already handled)
ALTER TABLE ONLINE_ORDERS       MODIFY COLUMN order_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE ONLINE_PRODUCTS     MODIFY COLUMN online_product_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE INVENTORY           MODIFY COLUMN inventory_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE TRANSACTION_ITEMS   MODIFY COLUMN item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE PAYMENTS            MODIFY COLUMN payment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE RETURNS             MODIFY COLUMN return_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE STOCK_MOVEMENTS     MODIFY COLUMN movement_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE EMAIL_LOGS          MODIFY COLUMN email_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE CART_ITEMS          MODIFY COLUMN cart_item_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE SESSION_TOKENS      MODIFY COLUMN token_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE AUDIT_LOG           MODIFY COLUMN log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT;

-- Re-enable FK checks
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
